name: example
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_trimmer:
    path: ../

  video_player:
    git:
      url: https://github.com/frank-dating/plugins
      path: packages/video_player/video_player
  file_picker: ^4.5.1

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
